### ISSUE TITLE
value for MODEL_dir and output_dir in pred.sh

### ISSUE THREAD

**Issue by cishwarya** [xlhex/extract_and_transfer#1]
Dear all, I am new to BERT/transformers.

I am trying to run the git repo
First I executed **train_vic.sh** and it got completed successfully and the results were saved under **home/extract_and_transfer/blog/vic/1234/**

This directory has the following files.
config.json
eval_results.txt
pytorch_model.bin
special_tokens_map.json
tokenizer_config.json
training_args.bin
vocab.txt

Now I wanted to query the victim model and executed **pred.sh** with below values. 
Note: "/home/extract_and_transfer/output" is an empty directory to save predictions

```
pred.sh
=====

TASK_NAME=$1
GLUE_DIR=data/$TASK_NAME/
SEED=$2
MODEL_dir=
OUTPUT=/home/extract_and_transfer/output

python predict.py \
    --model_type bert \
    --model_name_or_path bert-base-uncased \
    --task_name $TASK_NAME \
    --do_predict \
    --predict_input_file $GLUE_DIR/${3} \
    --predict_output_file $GLUE_DIR/${4} \
    --do_lower_case \
    --data_dir $GLUE_DIR/ \
    --max_seq_length 128 \
    --per_gpu_train_batch_size 64 \
    --per_gpu_eval_batch_size 64 \
    --defense $5 \
    --seed $2 \
    --output_dir  $OUTPUT  #> $output 2>&1
```

On executing pred.sh it throws the following error
```
$ sh pred.sh $TASK $SEED $QUERY_FILE $PRED_FILE $DEFENSE
pred.sh: 2: pred.sh: ===============================================================================: not found
07/09/2021 13:50:03 - WARNING - __main__ -   Process rank: -1, device: cuda, n_gpu: 4, distributed training: False, 16-bits training: False
Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.bias', 'cls.seq_relationship.weight', 'cls.predictions.bias', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at bert-base-uncased and are newly initialized: ['classifier.weight', 'classifier.bias']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "predict.py", line 455, in <module>
    main()
  File "predict.py", line 437, in main
    tokenizer = tokenizer_class.from_pretrained(args.output_dir, do_lower_case=args.do_lower_case)
  File "/home/hacker2/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 1708, in from_pretrained
    raise EnvironmentError(msg)
OSError: Can't load tokenizer for '/home/extract_and_transfer/output'. Make sure that:

- '/home/extract_and_transfer/output' is a correct model identifier listed on 'https://huggingface.co/models'

- or '/home/extract_and_transfer/output' is the correct path to a directory containing relevant tokenizer files
```

Could you please let me know how to solve this issue?

**Comment by xlhex** [comment]
> 
> Could you please let me know how to solve this issue?

**Comment by xlhex** [comment]
Hi,
Since you specified the output dir as: `home/extract_and_transfer/blog/vic/1234/`, `OUTPUT` in `predict.sh` should be set to `home/extract_and_transfer/blog/vic/1234/` as well. @cishwarya

**Comment by cishwarya** [comment]
Hi @xlhex after specifying the OUTPUT path as blog/vic/1234 it worked. Thanks

**Comment by xlhex** [comment]
issue resolved
